### ISSUE TITLE
Always got error API key is invalid

### ISSUE THREAD

**Issue by SastraNababan** [jwplayer/jwplatform-node#11]
I tried few times with my credential from https://dashboard.jwplayer.com/#/account/apicredentials
but always got this error
```
{ status: 'error',
        message: 'api_key: API key xxxxx is invalid',
        code: 'ParameterInvalid',
        title: 'Invalid Parameter' } } }
```

**Comment by boyntoni** [comment]
Hi Sastra,

Would you be able to provide me the e-mail associated with your account and site ID associated with the property you are trying to use the API for? I'd like to try to reproduce on my end.

Best,

Ian
