### ISSUE TITLE
replacing existing video

### ISSUE THREAD

**Issue by hfllr** [jwplayer/jwplatform-node#13]
When using

const response = await path == null ? jwApi.videos.update(data) : jwApi.videos.update(data, path)

the first case i.e. updating the title and description of a specific video works fine.
But replacing the video doesn't actually replace it even though everything else gets updated as expected.
Am I calling the update function incorrectly?

**Comment by boyntoni** [comment]
Hi @hfllr,

Sorry for the delay in getting back to you. In order to update an existing media, you must set an additional parameter `update_file: true`.

For example:

```
jwApi.videos.update({ video_key: 'key_to_update', sourcetype: 'file', update_file: true })
```

If you provide a `download_url`, this will perform a fetch upload, whereas without specifying it, the response will contain a link property, which contains data to construct an upload URL.

Please let me know if you have any questions.

**Comment by hfllr** [comment]
Thanks for your answer! @boyntoni 

I included all these parameters now but specifying the download_url doesn't work when I assign it with my variable 'path', which is a path to a local file that should replace the old one. Did I get something wrong there?
 
Also the link property you mentioned generates a new video key. Does that mean the old video object gets deleted and replaced including a new video key? 
It's a bit confusing for me how that update process works internally.

**Comment by boyntoni** [comment]
Hi @hfllr,

If you are trying to re-upload a local file, you should do something like the code sample below.

They key returned in the `link` dict will be different, but you should see that `response.media.key` is the same video key (or Media ID) specified in the update call.

```
const resolve = require('path').resolve;
const fs = require('fs');
const rp = require('request-promise');

const videoData = { video_key: {YOUR_VIDEO_KEY}, update_file: true, sourcetype: 'file' }

const filePath = './relative_path_to_file.mp4';
jwApi.videos.update(videoData).then(response => {
    const { path, protocol, address } = response.link;
    const uploadUrl = `${protocol}://${address}${path}`;
    return rp({
        method: 'POST',
        uri: uploadUrl,
        json: true,
        formData: {
            file: fs.createReadStream(resolve(filePath)),
        },
        qs: Object.assign({}, response.link.query, {
            api_format: 'json',
        }),
    }).then(resp => console.log(resp));
});
```

**Comment by hfllr** [comment]
Thanks a lot for the detailed response! It's working now. @boyntoni
