### ISSUE TITLE
Direct S3 upload from browser has CORS error

### ISSUE THREAD

**Issue by iamakimmer** [jwplayer/jwplatform-node#19]
I can create a s3 upload link using this:

```
  const res = await jwApi.videos.create({
    upload_method: 's3',
  });
```

This returns me a url: 

https://jwplatform-upload.s3-accelerate.amazonaws.com/secretlink...

But I cannot use this to directly upload from the browser as there's a CORS error:

Access to XMLHttpRequest at 'https://jwplatform-upload.s3-accelerate.amazonaws.com/secretlink' from origin 'https://mywebsite.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Is there any way I can do direct browser uploading to the s3 url? Or do I have to upload the file somewhere else first?

**Comment by MaxChu23** [comment]
Having the same issue now. @iamakimmer any news? :)

**Comment by iamakimmer** [comment]
I just made it a true html based submit form with a direct POST and no XHR. I think that's how you have to do it.

**Comment by dYale** [comment]
@iamakimmer @MaxChu23 Thanks for your discussion here. 

As noted in the Readme:

> this is not developed for client side use

We do not have plans to support a browser version in the near future. Please continue to submit issues as you find them.

**Comment by MaxChu23** [comment]
I just used it like this: using this API to generate a URL with Signature and other parameters and pass it to client side.
Now it doesn't have CORS issue, but only the "Signature doesn't match" error even though the Signature was sent how it's supposed to be sent (by converting it with `encodeURIComponent`). Also, changing `api_format` in query params to `json` doesn't change the response to `JSON` format.

Maybe it's that I'm using browser's fetch and not `request-promise` lib for that?

**Comment by iamakimmer** [comment]
as @dYale said, you can’t submit a video via browser with fetch or any library that’s going to do an xhr type post. I’ve been able to do a browser upload using a pure html form post.
