### ISSUE TITLE
API_KEY ERROR 

### ISSUE THREAD

**Issue by nobleson** [jwplayer/jwplatform-node#20]
Please i need help.
I have created an accound and added a credential on V2 section, where i am given an API KEY and Secrete , I then used the basic fuction tion intiate the platform.
const JWPlatformAPI = require('jwplatform');
const jwApiInstance = new JWPlatformAPI({
    apiKey:'tivcast-player',
    apiSecret: 'XXXXXXXXXXXXXXXX',
});

I tried to check my players
jwApiInstance.players.list().then(response => console.log(response));

I got this error:
Unhandled rejection StatusCodeError: 400 - {"status":"error","code":"ParameterInvalid","title":"Invalid Parameter","message":"api_key: API key tivcast-player is invalid"}

**Comment by boyntoni** [comment]
Hi @nobleson,

The API you are using to instantiate the client appears incorrect. You can find the correct API Key in the [API Credentials](https://support.jwplayer.com/articles/how-to-find-your-api-key-and-secret) section of our Dashboard.
